{
 "title": "Kubernetes Nginx Ingress",
 "description": "Show stats from the kubernetes nginx ingress",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Server Connections Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Server Reloads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_controller_success[1m]))",
     "legendFormat": "Reloads per min"
    }
   ]
  },
  {
   "title": "Server Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Server Requests by zone",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total{server_zone!~\"^.$\"}[1m])) by (server_zone)",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total[1m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone!~\"^.$\"}[1m])) by (server_zone)",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_upstream_responses_total[1m])) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_upstream_response_msecs_avg",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}