{
 "title": "Kubernetes App Metrics",
 "description": "After selecting your namespace and container you get a wealth of metrics like request rate, error rate, response times, pod count, cpu and memory usage. You can view cpu and memory usage in a variety of ways, compared to the limit, compared to the request, per pod, average per pod, etc.",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\"},container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Pod health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^($container).*$\",namespace=~\"^($namespace).*$\"}) / sum(kube_deployment_status_replicas{deployment=~\"^($container).*$\",namespace=~\"^($namespace).*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
     "legendFormat": "hosts"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^($container).*$\", namespace=\"$namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Running\",pod=~\"^($container).*$\", namespace=\"$namespace\"} == 1 and kube_pod_status_phase{phase!=\"Pending\",pod=~\"^($container).*$\", namespace=\"$namespace\"} == 1"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^($container).*$\",namespace=~\"^($namespace).*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"^($container).*$\",namespace=~\"^($namespace).*$\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"^($container).*$\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\", pod_name=~\"^($container).*$\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=~\"^($container).*$\", namespace=\"$namespace\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^($container).*$\",namespace=~\"^($namespace).*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^($container).*$\",namespace=~\"^($namespace).*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "Usage per pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=~\"$container\", namespace=\"$namespace\"}[60s])) by (id,pod_name)",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container_name=~\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "limit {{container_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_shares{container_name=~\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "request {{container_name}}"
      }
     ]
    },
    {
     "title": "Memory usage (per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (id,pod_name)",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (container_name,namespace)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Network I/O (per pod)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($container).*$\",namespace=\"$namespace\"}[1m])) by (pod_name)",
       "legendFormat": "-> {{pod_name}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($container).*$\",namespace=\"$namespace\"}[1m])) by (pod_name)",
       "legendFormat": "<- {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage relative to request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (relative to request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_system_seconds_total{container_name=~\"^$container$\", namespace=\"$namespace\"}[60s])) by (namespace,container_name) / sum(container_spec_cpu_shares{container_name=~\"^$container$\", namespace=\"$namespace\"} / 1024) by (namespace,container_name)",
       "legendFormat": "system {{container_name}}"
      },
      {
       "expr": "sum(irate(container_cpu_user_seconds_total{container_name=~\"^$container$\", namespace=\"$namespace\"}[60s])) by (namespace,container_name) / sum(container_spec_cpu_shares{container_name=~\"^$container$\", namespace=\"$namespace\"} / 1024) by (namespace,container_name)",
       "legendFormat": "user {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage per pod (average)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (avg per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=~\"^$container$\", namespace=\"$namespace\"}[60s])) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "actual  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container_name=~\"^$container$\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "limit  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_shares{container_name=~\"^$container$\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "request  {{container_name}}"
      }
     ]
    },
    {
     "title": "Memory usage (avg per pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "actual  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) ",
       "legendFormat": "limit  {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (total)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=~\"^$container$\", namespace=\"$namespace\"}[60s])) by (namespace,container_name)",
       "legendFormat": "actual  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container_name=~\"^$container$\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "limit  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_cpu_shares{container_name=~\"^$container$\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) ",
       "legendFormat": "request  {{container_name}}"
      }
     ]
    },
    {
     "title": "Memory usage (total)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "actual  {{container_name}}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "limit  {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage relative to limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (relative to limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=~\"^$container$\", namespace=\"$namespace\"}[60s])) by (namespace,container_name) / sum(container_spec_cpu_quota{container_name=~\"^$container$\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "actual  {{container_name}}"
      }
     ]
    },
    {
     "title": "Memory usage (relative to limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name) / sum(container_spec_memory_limit_bytes{container_name=~\"^$container$\", namespace=\"$namespace\"}) by (namespace,container_name)",
       "legendFormat": "actual  {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_requests_total{app=~\"^$container$\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[60s])) by (kubernetes_namespace,app,code)",
       "legendFormat": "native | {{code}}"
      },
      {
       "expr": "sum(irate(nginx_http_requests_total{app=~\"^$container$\", kubernetes_namespace=\"$namespace\"}[60s])) by (kubernetes_namespace,app,status)",
       "legendFormat": "nginx | {{status}}"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{app=~\"^$container$\", kubernetes_namespace=\"$namespace\"}[60s])) by (app,kubernetes_namespace,code)",
       "legendFormat": "haproxy | {{code}}"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\",code=\"5xx\"}[60s])) by (app,kubernetes_namespace) / sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace)",
       "legendFormat": "haproxy"
      },
      {
       "expr": "sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\", code=~\"5[0-9]+\"}[60s])) by (kubernetes_namespace,app) / sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
       "legendFormat": "native"
      },
      {
       "expr": "sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\", status=~\"5[0-9]+\"}[60s])) by (kubernetes_namespace,app) / sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
       "legendFormat": "nginx"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time percentiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[60s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.50"
      }
     ]
    }
   ]
  }
 ]
}